### ISSUE TITLE
NetworkBehaviour driver error after update to V0.54

### ISSUE THREAD

**Issue by xG0Ian** [libp2p/rust-libp2p#5544]
### Summary

error[E0050]: method `handle_established_outbound_connection` has 5 parameters but the declaration in trait `handle_established_outbound_connection` has 6
 --> src/xxx/behaviours.rs:3:10
  |
3 | #[derive(NetworkBehaviour)]
  |          ^^^^^^^^^^^^^^^^ expected 6 parameters, found 5
  |
  = note: `handle_established_outbound_connection` from trait: `fn(&mut Self, ConnectionId, PeerId, &libp2p::Multiaddr, libp2p::libp2p_core::Endpoint, PortUse) -> Result<<Self as NetworkBehaviour>::ConnectionHandler, ConnectionDenied>`
  = note: this error originates in the derive macro `NetworkBehaviour` (in Nightly builds, run with -Z macro-backtrace for more info)

### Expected behavior

I trun it back to V0.53, it works.

Is there any break API changed?

### Actual behavior

build error

### Version

version: V0.54

branch: master

### Would you like to work on fixing this bug ?

Yes

**Comment by ok-ul-ch** [comment]
It seems that [libp2p-swarm-derive](https://crates.io/crates/libp2p-swarm-derive/versions) has not bee released as part of 0.54 `libp2p` release

**Comment by xG0Ian** [comment]
Hmm... maybe it's my system environment s fault.

I built the same project on my WSL deps libp2p(V0.53), got this:
```
error[E0599]: `BandwidthTransport<T>` is not an iterator
```
But it built successfully on my another PC, I will check it on Monday.

**Comment by jxs** [comment]
Hi, and sorry for the inconvenience, this should have been addressed with https://github.com/libp2p/rust-libp2p/pull/5545 can you confirm?

**Comment by xG0Ian** [comment]
Yes! It's working for me now after rebuilt, thanks for your help @jxs ! 😸 I will close this issue.
